/** Romanian user-facing API error messages */
export const apiErrors = {
  unauthorized: 'Neautorizat',
  forbidden: 'Acces interzis',
  notFound: 'Nu a fost găsit',
  internalServerError: 'Eroare internă de server',
  failedToFetch: 'Încărcarea datelor a eșuat',
  failedToCreate: 'Crearea a eșuat',
  failedToUpdate: 'Actualizarea a eșuat',
  failedToDelete: 'Ștergerea a eșuat',
  invalidInput: 'Date introduse invalide',
  noActionsToUndo: 'Nu există acțiuni de anulat',
  procedureNotFound: 'Procedura nu a fost găsită',
  noBackupDelete: 'Nu s-a găsit copie de rezervă pentru procedura ștearsă',
  noBackupEdit: 'Nu s-a găsit copie de rezervă pentru procedura editată',
  unsupportedAction: 'Acțiune neacceptată pentru anulare',
  reminderNotFound: 'Memento negăsit',
  failedToUpdateReminder: 'Actualizarea mementoului a eșuat',
  taskNotFound: 'Sarcina nu a fost găsită sau permisiuni insuficiente',
  failedToFetchAssignments: 'Încărcarea atribuirilor a eșuat',
  failedToCreateSealing: 'Crearea procedurilor de sigilare a eșuat',
  registrationFailed: 'Înregistrarea a eșuat',
  validationFailed: 'Validarea a eșuat',
  failedToSendEmail: 'Trimiterea e-mailului a eșuat',
  failedToExport: 'Exportul a eșuat',
  patientNotFound: 'Pacientul nu a fost găsit',
  appointmentNotFound: 'Programarea nu a fost găsită',
  organizationNotFound: 'Organizația nu a fost găsită',
  userNotFound: 'Utilizatorul nu a fost găsit',
  failedToUpload: 'Încărcarea a eșuat',
  failedToDownload: 'Descărcarea a eșuat',
  invalidCredentials: 'Date de autentificare invalide',
  emailAlreadyExists: 'Adresa de e-mail este deja înregistrată',
  failedToProcess: 'Procesarea a eșuat',
  failedToSave: 'Salvarea a eșuat',
  failedToLoad: 'Încărcarea a eșuat',
  noPermission: 'Nu aveți permisiunea necesară',
  sessionExpired: 'Sesiunea a expirat. Autentificați-vă din nou.',
} as const

export type ApiErrorKey = keyof typeof apiErrors
