export interface MedicationSeed {
  sortOrder: number
  name: string
  aliases?: string[]
  requiresFridge?: boolean
  form?: string
  stockFarmacia?: number
  activeIngredient?: string
  usageInstructions: string
  prescriptionTemplate: string
  notes?: string
}

function rx(name: string, ingredient: string, posology: string, warnings?: string): string {
  const warn = warnings ? `\n\nAtenție: ${warnings}` : ''
  return `REȚETĂ MEDICALĂ

Pacient: _________________________   CNP: _________________________
Data: _________________________

Rp/
${name}
(${ingredient})

${posology}

Semnătura și parafa medicului: _________________________
${warn}`
}

function instr(sections: Record<string, string>): string {
  return Object.entries(sections)
    .map(([title, body]) => `${title}:\n${body}`)
    .join('\n\n')
}

export const CLINIC_MEDICATION_SEED: MedicationSeed[] = [
  { sortOrder: 1, name: 'ACUPAN', activeIngredient: 'Nefopam', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Analgezic central pentru durere postoperatorie moderată.', Administrare: 'IV/IM conform protocolului clinicii. Monitorizare tensiune arterială.', Contraindicații: 'Epilepsie necontrolată, glaucom acut.' }), prescriptionTemplate: rx('Acupan', 'Nefopam', 'Se administrează conform protocolului postoperator al clinicii.') },
  { sortOrder: 2, name: 'ADRENALINA', aliases: ['EPINEPHRINA'], activeIngredient: 'Adrenalină', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Urgențe anafilaxie, resuscitare, vasoconstrictor local.', Administrare: 'IM 0.3–0.5 mg în anafilaxie; diluții pentru perfuzie conform ACLS.', Atenție: 'Monitorizare ECG și TA; evitați extravasare.' }), prescriptionTemplate: rx('Adrenalină', 'Epinefrină', 'Pentru uz în urgență conform protocolului clinic.') },
  { sortOrder: 3, name: 'ADRENOSTAZIN', activeIngredient: 'Adrenalină + vitamina K', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Hemostază locală.', Administrare: 'Aplicare topică/locală conform indicației chirurgicale.' }), prescriptionTemplate: rx('Adrenostazin', 'Adrenalină + fitomenadion', 'Aplicare locală conform indicației medicale.') },
  { sortOrder: 4, name: 'ALGIFIN', activeIngredient: 'Paracetamol', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Durere ușoară-moderată, febră.', Administrare: 'IV/perfuzie conform greutății corporale; max 4 g/zi la adult.', Atenție: 'Evitați supradozajul hepatic.' }), prescriptionTemplate: rx('Algifin', 'Paracetamol', '1 flacon IV la nevoie, max 4 doze/zi.') },
  { sortOrder: 5, name: 'ALGOCALMIN', activeIngredient: 'Metamizol', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Durere moderată-severă, antipiretic.', Administrare: 'IV/IM lent; monitorizare reacții alergice.', Atenție: 'Risc agranulocitoză – opriți la febră inexplicabilă.' }), prescriptionTemplate: rx('Algocalmin', 'Metamizol sodic', '1 ampulă IV/IM la 6–8 ore, după necesitate.') },
  { sortOrder: 6, name: 'ALBUMINA', activeIngredient: 'Albumină umană', stockFarmacia: 5, requiresFridge: true, form: 'perfuzie', usageInstructions: instr({ Indicații: 'Hipovolemie, hipoalbuminemie, suport perioperator.', Administrare: 'Perfuzie IV lentă; temperatură 2–8°C.', Depozitare: 'Păstrați la frigider. Nu înghețați.' }), prescriptionTemplate: rx('Albumină umană 20%', 'Albumină', 'Perfuzie IV conform calculului de deficit.') },
  { sortOrder: 7, name: 'ANEXATE', activeIngredient: 'Flumazenil', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Antidot pentru supradozaj benzodiazepine.', Administrare: 'IV lent, titrare la răspuns clinic; risc convulsii la epileptici.' }), prescriptionTemplate: rx('Anexate', 'Flumazenil', '0.2 mg IV lent, repetare la 1 min dacă este necesar.') },
  { sortOrder: 8, name: 'BETADINA UNGUENT', activeIngredient: 'Povidon iodat', stockFarmacia: 1, form: 'unguent', usageInstructions: instr({ Indicații: 'Antiseptic local pentru plăgi și pregătire perianală.', Administrare: 'Aplicare strat subțire pe zona curățată.' }), prescriptionTemplate: rx('Betadina unguent', 'Povidon iodat 10%', 'Aplicare locală de 2 ori/zi pe zona afectată.') },
  { sortOrder: 9, name: 'BETALOC', activeIngredient: 'Metoprolol', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Tahicardie, HTA perioperatorie, profilaxie aritmii.', Administrare: 'IV lent; monitorizare FC și TA.' }), prescriptionTemplate: rx('Betaloc', 'Metoprolol tartrat', '5 mg IV lent, repetare după 5 min dacă este necesar.') },
  { sortOrder: 10, name: 'BICARBONAT INJ', activeIngredient: 'Bicarbonat de sodiu', form: 'injectabil', usageInstructions: instr({ Indicații: 'Acidoză metabolică, hiperkaliemie.', Administrare: 'IV lent; verificați gazele sangvine.' }), prescriptionTemplate: rx('Bicarbonat de sodiu', 'NaHCO3', 'Perfuzie IV conform calculului de deficit bazic.') },
  { sortOrder: 11, name: 'CALIPSOL', activeIngredient: 'Ketamină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Anestezie disociativă, analgezie.', Administrare: 'IV/IM conform protocolului de anestezie.', Atenție: 'Crește secrețiile – considerați atropină.' }), prescriptionTemplate: rx('Calipsol', 'Ketamină', 'Doza conform protocolului anestezic.') },
  { sortOrder: 12, name: 'CEFORT', activeIngredient: 'Ceftriaxonă', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Antibiotic profilactic/terapeutic.', Administrare: 'IV/IM; reconstituire conform prospectului.', Atenție: 'Alergie la peniciline – evaluare risc încrucișat.' }), prescriptionTemplate: rx('Cefort', 'Ceftriaxonă 1 g', '1 g IV/IM o dată/zi.') },
  { sortOrder: 13, name: 'CLEXANE 4000', activeIngredient: 'Enoxaparină', stockFarmacia: 1, form: 'seringă preumplută', usageInstructions: instr({ Indicații: 'Profilaxie tromboembolism.', Administrare: 'SC; nu masați zona de injectare.' }), prescriptionTemplate: rx('Clexane 4000 UI', 'Enoxaparină', '0.4 ml SC o dată/zi.') },
  { sortOrder: 14, name: 'CLEXANE 6000', activeIngredient: 'Enoxaparină', stockFarmacia: 1, form: 'seringă preumplută', usageInstructions: instr({ Indicații: 'Profilaxie/tratament tromboembolism.', Administrare: 'SC conform greutății și riscului.' }), prescriptionTemplate: rx('Clexane 6000 UI', 'Enoxaparină', '0.6 ml SC o dată/zi.') },
  { sortOrder: 15, name: 'CONTROLOC / OMEPRAZOL', aliases: ['CONTROLOC', 'OMEPRAZOL'], activeIngredient: 'Omeprazol', usageInstructions: instr({ Indicații: 'Profilaxie ulcer de stres, dispepsie.', Administrare: 'IV/PO; administrare dimineața.' }), prescriptionTemplate: rx('Controloc', 'Omeprazol 40 mg', '1 flacon IV sau 1 capsulă/zi dimineața.') },
  { sortOrder: 16, name: 'CIPRINOL', activeIngredient: 'Ciprofloxacină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Antibiotic fluorochinolonă.', Administrare: 'IV perfuzie lentă; hidratare adecvată.', Atenție: 'Evitați la copii; risc tendinită.' }), prescriptionTemplate: rx('Ciprinol', 'Ciprofloxacină 200 mg', '200 mg IV la 12 ore.') },
  { sortOrder: 17, name: 'DEXAMETAZONA / DEXAMED', aliases: ['DEXAMETAZONA', 'DEXAMED'], activeIngredient: 'Dexametazonă', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Antiinflamator, profilaxie greață postoperatorie, edem.', Administrare: 'IV/IM conform protocolului.' }), prescriptionTemplate: rx('Dexametazonă', 'Dexametazonă 4 mg', '4–8 mg IV o dată sau conform protocolului PONV.') },
  { sortOrder: 18, name: 'DERMOBACTER', activeIngredient: 'Clorhexidină', stockFarmacia: 1, form: 'soluție', usageInstructions: instr({ Indicații: 'Antiseptic cutanat preoperator.', Administrare: 'Aplicare pe piele curată și uscată.' }), prescriptionTemplate: rx('Dermobakter', 'Clorhexidină', 'Aplicare topică preoperatorie.') },
  { sortOrder: 19, name: 'DIPROPHOS', activeIngredient: 'Betametazonă', stockFarmacia: 1, usageInstructions: instr({ Indicații: 'Antiinflamator steroid injectabil.', Administrare: 'IM/IV conform indicației; evitați utilizare prelungită.' }), prescriptionTemplate: rx('Diprophos', 'Betametazonă', '1 ampulă IM/IV conform indicației medicale.') },
  { sortOrder: 20, name: 'DIAZEPAM', activeIngredient: 'Diazepam', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Ansiolitic, anticonvulsiv, sedare.', Administrare: 'IV lent; risc depresie respiratorie.', Atenție: 'Substanță controlată – evidență obligatorie.' }), prescriptionTemplate: rx('Diazepam', 'Diazepam 10 mg', '5–10 mg IV lent conform indicației.') },
  { sortOrder: 21, name: 'DEVIT3 D3', activeIngredient: 'Colecalciferol', stockFarmacia: 1, usageInstructions: instr({ Indicații: 'Supliment vitamina D.', Administrare: 'IM/PO conform nivelului seric.' }), prescriptionTemplate: rx('Devit 3', 'Colecalciferol', 'Doza conform deficitului de vitamina D.') },
  { sortOrder: 22, name: 'EFEDRINA', activeIngredient: 'Efedrină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Hipotensiune intraoperatorie.', Administrare: 'IV bolusuri titrate; monitorizare TA și FC.' }), prescriptionTemplate: rx('Efedrină', 'Efedrină 30 mg', '5–10 mg IV la nevoie pentru TA scăzută.') },
  { sortOrder: 23, name: 'ENAP', activeIngredient: 'Enalapril', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'HTA, insuficiență cardiacă.', Administrare: 'PO/IV; monitorizare funcție renală și potasiu.' }), prescriptionTemplate: rx('Enap', 'Enalapril', 'Doza conform TA și funcției renale.') },
  { sortOrder: 24, name: 'ESMERON', activeIngredient: 'Rocuroniu', stockFarmacia: 10, requiresFridge: true, usageInstructions: instr({ Indicații: 'Relaxant muscular pentru intubare și chirurgie.', Administrare: 'IV; pregătire reversie cu Sugammadex disponibilă.', Depozitare: 'Păstrați la frigider 2–8°C.' }), prescriptionTemplate: rx('Esmeron', 'Rocuroniu bromură', 'Doza IV conform evaluării anestezice.') },
  { sortOrder: 25, name: 'ETAMISILAT', activeIngredient: 'Etamsilat', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Hemostatice, reducere sângerare capilară.', Administrare: 'IV/IM pre/postoperator.' }), prescriptionTemplate: rx('Etamsilat', 'Etamsilat', '1–2 ampule IV/IM la nevoie.') },
  { sortOrder: 26, name: 'FENTANYL', activeIngredient: 'Fentanil', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Analgezie puternică, anestezie.', Administrare: 'IV lent; monitorizare respiratorie.', Atenție: 'Opioid – evidență obligatorie.' }), prescriptionTemplate: rx('Fentanyl', 'Fentanil', 'Doza IV titrată în bloc operator.') },
  { sortOrder: 27, name: 'FENOBARBITAL', activeIngredient: 'Fenobarbital', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Anticonvulsiv, sedare.', Administrare: 'IV lent; monitorizare nivel de conștiență.', Atenție: 'Substanță controlată.' }), prescriptionTemplate: rx('Fenobarbital', 'Fenobarbital', 'Doza IV conform indicației neurologice.') },
  { sortOrder: 28, name: 'FITOMENADION', activeIngredient: 'Vitamina K1', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Coagulopatie, profilaxie sângerare la anticoagulare.', Administrare: 'IV lent sau IM.' }), prescriptionTemplate: rx('Fitomenadion', 'Vitamina K1', '10 mg IV lent.') },
  { sortOrder: 29, name: 'FORVEL', activeIngredient: 'Paracetamol', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Analgezie, antipiretică.', Administrare: 'IV perfuzie în 15 min.' }), prescriptionTemplate: rx('Forvel', 'Paracetamol 1 g', '1 g IV la 6 ore după necesitate.') },
  { sortOrder: 30, name: 'FLUIMUCIL', activeIngredient: 'Acetilcisteină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Mucolitic, antidot paracetamol (doză mare).', Administrare: 'IV/inalator conform indicației.' }), prescriptionTemplate: rx('Fluimucil', 'Acetilcisteină', '600 mg IV sau nebulizare conform protocolului.') },
  { sortOrder: 31, name: 'FUROSEMID', activeIngredient: 'Furosemid', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Diuretic, edem pulmonar acut.', Administrare: 'IV lent; monitorizare electroliți.' }), prescriptionTemplate: rx('Furosemid', 'Furosemid 40 mg', '20–40 mg IV lent.') },
  { sortOrder: 32, name: 'GENTAMICINA', activeIngredient: 'Gentamicină', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Antibiotic aminoglicozidic.', Administrare: 'IV/IM; monitorizare funcție renală.', Atenție: 'Nefrotoxic – ajustare doză renală.' }), prescriptionTemplate: rx('Gentamicină', 'Gentamicină', 'Doza IV conform funcției renale.') },
  { sortOrder: 33, name: 'GLUCONAT DE CALCIU', activeIngredient: 'Gluconat de calciu', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Hipocalcemie, hiperkaliemie, hipotensiune la transfuzie.', Administrare: 'IV foarte lent; monitorizare ECG.' }), prescriptionTemplate: rx('Gluconat de calciu 10%', 'Calciu', '10 ml IV lent sub monitorizare.') },
  { sortOrder: 34, name: 'HIDROCORTIZON', activeIngredient: 'Hidrocortizon', stockFarmacia: 1, usageInstructions: instr({ Indicații: 'Insuficiență adrenală, reacție alergică severă.', Administrare: 'IV bolus în urgență.' }), prescriptionTemplate: rx('Hidrocortizon', 'Hidrocortizon 100 mg', '100 mg IV în urgență.') },
  { sortOrder: 35, name: 'LIDOCAIN', activeIngredient: 'Lidocaină', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Anestezie locală, antiaritmic.', Administrare: 'Infiltrație locală sau IV conform protocolului.' }), prescriptionTemplate: rx('Lidocaină', 'Lidocaină 2%', 'Infiltrație locală sau doză IV antiaritmică.') },
  { sortOrder: 36, name: 'LYSTHENON', activeIngredient: 'Neostigmină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Reversie blocaj neuromuscular (cu atropină/glicopirrolat).', Administrare: 'IV lent după evaluare TOF.' }), prescriptionTemplate: rx('Lysthenon', 'Neostigmină', '0.05 mg/kg IV cu atropină, conform protocolului.') },
  { sortOrder: 37, name: 'LIDOCAINA SPRAY', activeIngredient: 'Lidocaină', stockFarmacia: 1, form: 'spray', usageInstructions: instr({ Indicații: 'Anestezie topică mucoase (gat, nazal).', Administrare: '1–2 pulverizări; evitați supradozajul.' }), prescriptionTemplate: rx('Lidocaină spray', 'Lidocaină 10%', '1–2 aplicări topic pe mucoasă.') },
  { sortOrder: 38, name: 'GRANISETRON', activeIngredient: 'Granisetron', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Antiemetic pentru greață/vărsături postoperatorii.', Administrare: 'IV lent înainte de finalul anesteziei.' }), prescriptionTemplate: rx('Granisetron', 'Granisetron 3 mg', '3 mg IV o dată.') },
  { sortOrder: 39, name: 'KETOPROFEN', activeIngredient: 'Ketoprofen', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'AINS pentru durere și inflamație.', Administrare: 'IV/IM; administrare cu masă.', Atenție: 'Evitați la ulcer gastric activ.' }), prescriptionTemplate: rx('Ketoprofen', 'Ketoprofen 100 mg', '100 mg IV/IM la 12 ore.') },
  { sortOrder: 40, name: 'METRONIDAZOL', activeIngredient: 'Metronidazol', usageInstructions: instr({ Indicații: 'Antibiotic/antiparazitar anaerob.', Administrare: 'IV perfuzie lentă; evitați alcoolul.' }), prescriptionTemplate: rx('Metronidazol', 'Metronidazol 500 mg', '500 mg IV la 8 ore.') },
  { sortOrder: 41, name: 'METOCLOPRAMID', activeIngredient: 'Metoclopramid', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Antiemetic, prokinetic.', Administrare: 'IV lent; risc extrapiramidal la tineri.' }), prescriptionTemplate: rx('Metoclopramid', 'Metoclopramid 10 mg', '10 mg IV la nevoie.') },
  { sortOrder: 42, name: 'MIDAZOLAM', activeIngredient: 'Midazolam', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Sedare, anxioliză preoperatorie.', Administrare: 'IV lent titrat; Flumazenil disponibil.', Atenție: 'Substanță controlată.' }), prescriptionTemplate: rx('Midazolam', 'Midazolam', 'Doza IV titrată pentru sedare.') },
  { sortOrder: 43, name: 'MIALGIN', activeIngredient: 'Metamizol', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Analgezie.', Administrare: 'IV/IM; monitorizare reacții alergice.' }), prescriptionTemplate: rx('Mialgin', 'Metamizol', '1 ampulă IV/IM la 6–8 ore.') },
  { sortOrder: 44, name: 'MIOSTIN', activeIngredient: 'Neostigmină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Reversie curarizare.', Administrare: 'IV cu atropină/glicopirrolat.' }), prescriptionTemplate: rx('Miostin', 'Neostigmină', 'Conform protocolului de reversie neuromusculară.') },
  { sortOrder: 45, name: 'MIOFLIN', activeIngredient: 'Clorură de calciu', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Supliment calciu IV.', Administrare: 'IV lent sub monitorizare.' }), prescriptionTemplate: rx('Mioflin', 'Clorură de calciu', 'IV lent conform indicației.') },
  { sortOrder: 46, name: 'MORFINA ZENTIVA', activeIngredient: 'Morfina', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Analgezie severă.', Administrare: 'IV/SC titrat; monitorizare respiratorie.', Atenție: 'Opioid controlat – evidență obligatorie.' }), prescriptionTemplate: rx('Morfina', 'Morfina', 'Doza IV titrată pentru durere severă.') },
  { sortOrder: 47, name: 'NITRONAL', activeIngredient: 'Nitroglicerină', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Angină, HTA intraoperatorie.', Administrare: 'IV perfuzie titrată; monitorizare TA.' }), prescriptionTemplate: rx('Nitronal', 'Nitroglicerină', 'Perfuzie IV titrată conform TA.') },
  { sortOrder: 48, name: 'NO SPA FL.', aliases: ['NO-SPA'], activeIngredient: 'Drotaverină', stockFarmacia: 25, form: 'fiole', usageInstructions: instr({ Indicații: 'Antispastic pentru durere abdominală/colică.', Administrare: 'IV/IM.' }), prescriptionTemplate: rx('No-Spa', 'Drotaverină 40 mg', '40–80 mg IV/IM la nevoie.') },
  { sortOrder: 49, name: 'OSETRON', activeIngredient: 'Ondansetron', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Antiemetic.', Administrare: 'IV lent la finalul intervenției.' }), prescriptionTemplate: rx('Osetron', 'Ondansetron 8 mg', '8 mg IV o dată.') },
  { sortOrder: 50, name: 'SEVO ANESTERAN', activeIngredient: 'Sevoflurane', stockFarmacia: 1, form: 'anestezic volatil', usageInstructions: instr({ Indicații: 'Anestezie generală inhalatorie.', Administrare: 'Vaporizator calibrat; monitorizare anestezică.' }), prescriptionTemplate: rx('Sevoflurane', 'Sevoflurane', 'Administrare inhalatorie în bloc operator.') },
  { sortOrder: 51, name: 'SULFAT DE ATROPINA', activeIngredient: 'Atropină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Bradicardie, premedicație, reversie neostigmină.', Administrare: 'IV.' }), prescriptionTemplate: rx('Atropină', 'Atropină sulfat', '0.5–1 mg IV la nevoie.') },
  { sortOrder: 52, name: 'TAMALIS cutie 30 tab', aliases: ['TAMALIS'], activeIngredient: 'Tamoxifen', stockFarmacia: 1, form: 'comprimate', usageInstructions: instr({ Indicații: 'Terapie oncologică hormonă-dependentă.', Administrare: 'PO zilnic conform oncolog.' }), prescriptionTemplate: rx('Tamalis', 'Tamoxifen', '1 comprimat/zi conform protocolului oncologic.') },
  { sortOrder: 53, name: 'TACHYBEN', activeIngredient: 'Lidocaină + epinefrină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Anestezie locală cu vasoconstrictor.', Administrare: 'Infiltrație locală; respectați doza maximă lidocaină.' }), prescriptionTemplate: rx('Tachyben', 'Lidocaină + adrenalină', 'Infiltrație locală conform suprafeței operate.') },
  { sortOrder: 54, name: 'TRACRIUM', activeIngredient: 'Atracurium', usageInstructions: instr({ Indicații: 'Relaxant muscular intermediar.', Administrare: 'IV bolus sau perfuzie.' }), prescriptionTemplate: rx('Tracrium', 'Atracurium', 'Doza IV conform evaluării anestezice.') },
  { sortOrder: 55, name: 'TRAMADOL', activeIngredient: 'Tramadol', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Analgezie moderată.', Administrare: 'IV/IM/PO; risc convulsii la supradozaj.' }), prescriptionTemplate: rx('Tramadol', 'Tramadol 100 mg', '50–100 mg IV/IM la 6–8 ore.') },
  { sortOrder: 56, name: 'PARACETAMOL INJ', activeIngredient: 'Paracetamol', stockFarmacia: 10, form: 'injectabil', usageInstructions: instr({ Indicații: 'Analgezie, antipiretică.', Administrare: 'IV în 15 minute; max 4 g/zi.' }), prescriptionTemplate: rx('Paracetamol injectabil', 'Paracetamol 1 g', '1 g IV la 6 ore.') },
  { sortOrder: 57, name: 'PROPOFOL FRIGIDER', aliases: ['PROPOFOL'], activeIngredient: 'Propofol', stockFarmacia: 5, requiresFridge: true, usageInstructions: instr({ Indicații: 'Inducție și menținere anestezie generală, sedare.', Administrare: 'IV titrat; monitorizare continuă.', Depozitare: 'Păstrați la frigider 2–8°C.' }), prescriptionTemplate: rx('Propofol', 'Propofol 1%', 'Inducție IV titrată conform protocolului anestezic.') },
  { sortOrder: 58, name: 'PENTOXIFILINA', activeIngredient: 'Pentoxifilină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Îmbunătățire flux sanguin periferic.', Administrare: 'IV perfuzie lentă.' }), prescriptionTemplate: rx('Pentoxifilină', 'Pentoxifilină', 'Perfuzie IV conform protocolului.') },
  { sortOrder: 59, name: 'RINOFUG', activeIngredient: 'Soluție nasală', stockFarmacia: 1, form: 'spray nazal', usageInstructions: instr({ Indicații: 'Decongestionant/dezinfectant nazal.', Administrare: '1–2 pulverizări per nară.' }), prescriptionTemplate: rx('Rinofug', 'Soluție nazală', '1–2 aplicări nazale de 2–3 ori/zi.') },
  { sortOrder: 60, name: 'URAPIDIL CLACEKS', aliases: ['URAPIDIL'], activeIngredient: 'Urapidil', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Criză hipertensivă.', Administrare: 'IV bolus/perfuzie titrată.' }), prescriptionTemplate: rx('Urapidil', 'Urapidil 25 mg', '25 mg IV bolus, repetare după necesitate.') },
  { sortOrder: 61, name: 'VENTOLIN', activeIngredient: 'Salbutamol', stockFarmacia: 1, form: 'inhalator', usageInstructions: instr({ Indicații: 'Bronhospasm, astm.', Administrare: 'Inhalator 1–2 puffuri la nevoie.' }), prescriptionTemplate: rx('Ventolin', 'Salbutamol', '1–2 inhalări la nevoie.') },
  { sortOrder: 62, name: 'VENOFER', activeIngredient: 'Saccharat de hidroxid feric', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Anemie feriprivă.', Administrare: 'IV lent sau perfuzie.' }), prescriptionTemplate: rx('Venofer', 'Fier IV', 'Doza conform hemoglobinei și greutății.') },
  { sortOrder: 63, name: 'VANCOMICINA', activeIngredient: 'Vancomicină', stockFarmacia: 1, usageInstructions: instr({ Indicații: 'Antibiotic pentru germeni Gram-pozitivi rezistenți.', Administrare: 'IV perfuzie lentă ≥60 min; monitorizare funcție renală.' }), prescriptionTemplate: rx('Vancomicină', 'Vancomicină 1 g', '1 g IV perfuzie lentă la 12 ore.') },
  { sortOrder: 64, name: 'VITAMINA C', activeIngredient: 'Acid ascorbic', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Supliment, suport imunitar perioperator.', Administrare: 'IV/PO.' }), prescriptionTemplate: rx('Vitamina C', 'Acid ascorbic', '500 mg–1 g IV/zi.') },
  { sortOrder: 65, name: 'VITAMINA B1 si B6', activeIngredient: 'Tiamină + piridoxină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Supliment vitaminic.', Administrare: 'IV/IM.' }), prescriptionTemplate: rx('Vitamina B1 + B6', 'Tiamină + piridoxină', '1 ampulă IV/IM/zi.') },
  { sortOrder: 66, name: 'VITAMINA B12', activeIngredient: 'Cianocobalamină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Deficit B12, suport hematologic.', Administrare: 'IM/IV.' }), prescriptionTemplate: rx('Vitamina B12', 'Cianocobalamină', '1 ampulă IM săptămânal sau conform protocolului.') },
  { sortOrder: 67, name: 'XILINA', activeIngredient: 'Lidocaină', stockFarmacia: 5, usageInstructions: instr({ Indicații: 'Anestezie locală.', Administrare: 'Infiltrație; respectați doza maximă.' }), prescriptionTemplate: rx('Xilină', 'Lidocaină', 'Infiltrație locală conform procedurii.') },
  { sortOrder: 68, name: 'XANAX cutie 30 tab', aliases: ['XANAX'], activeIngredient: 'Alprazolam', stockFarmacia: 1, form: 'comprimate', usageInstructions: instr({ Indicații: 'Anxiolitic.', Administrare: 'PO; evitați combinarea cu alte sedative.', Atenție: 'Substanță controlată.' }), prescriptionTemplate: rx('Xanax', 'Alprazolam 0.25 mg', '0.25–0.5 mg PO la nevoie, max conform protocolului.') },
  { sortOrder: 69, name: 'KANAMICINA', activeIngredient: 'Kanamicină', stockFarmacia: 1, usageInstructions: instr({ Indicații: 'Antibiotic aminoglicozidic.', Administrare: 'IV/IM; monitorizare funcție renală.' }), prescriptionTemplate: rx('Kanamicină', 'Kanamicină', 'Doza IV conform funcției renale.') },
  { sortOrder: 70, name: 'DULCOLAX', activeIngredient: 'Bisacodil', stockFarmacia: 1, form: 'comprimate', usageInstructions: instr({ Indicații: 'Laxativ pentru constipație postoperatorie.', Administrare: 'PO seara; efect în 6–12 ore.' }), prescriptionTemplate: rx('Dulcolax', 'Bisacodil 5 mg', '5–10 mg PO seara.') },
  { sortOrder: 71, name: 'ARNIGEL UNG.', aliases: ['ARNIGEL'], activeIngredient: 'Arnica', stockFarmacia: 1, form: 'gel', usageInstructions: instr({ Indicații: 'Contuzii, echimoze postoperatorii.', Administrare: 'Aplicare topică pe piele intactă.' }), prescriptionTemplate: rx('Arnigel', 'Arnica gel', 'Aplicare topică de 2–3 ori/zi.') },
  { sortOrder: 72, name: 'SUGAMMADEX RECEP.', aliases: ['SUGAMMADEX'], activeIngredient: 'Sugammadex', stockFarmacia: 10, usageInstructions: instr({ Indicații: 'Reversie rapidă blocaj neuromuscular cu rocuroniu/vecuroniu.', Administrare: 'IV bolus conform greutății și TOF.' }), prescriptionTemplate: rx('Sugammadex', 'Sugammadex', '2–4 mg/kg IV pentru reversie imediată.') },
  { sortOrder: 73, name: 'FUCIDINA CREMA', aliases: ['FUCIDINA'], activeIngredient: 'Acid fusidic', stockFarmacia: 1, form: 'cremă', usageInstructions: instr({ Indicații: 'Infecții cutanate bacteriene.', Administrare: 'Aplicare topică de 2–3 ori/zi pe zona curată.' }), prescriptionTemplate: rx('Fucidin cremă', 'Acid fusidic', 'Aplicare topică de 2–3 ori/zi.') },
]
